config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks, only: [:create, :destroy]

  devise_for :accounts, :controllers =>{
      :registrations => 'accounts/registrations'
  }

  devise_scope :account do
    post '/accounts/sign_up/confirm', to: 'accounts/registrations#confirm'
    delete '/accounts/:id', to: 'accounts/registrations#destroy', as: :account_destroy, constraints: {id: /[0-9]+/ }
  end

  resources :recruitments, only: [ :edit, :update, :destroy ]
  post '/recruitments/create/:id', to: 'recruitments#create', as: :recruitments_create
  post '/recruitments/:id', to: 'recruitments#update', constraints: {id: /[0-9]+/ }
  # 返信追加読み込み
  post '/recruitments/edit/add/:id/:offset_time', to: 'recruitments#add_result', as: :results_add, constraints: { id:/[0-9]+/ }
  post '/recruitments/select/:id/:comment_id', to: 'recruitments#select', as: :select_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }
  post '/recruitments/selected/:id/:comment_id', to: 'recruitments#selected', as: :selected_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }

# 返信生成削除
  resources :comments, only: [ :create, :destroy ]
  get '/comments/index/:recruitment_id', to: 'comments#index', as: :comments_index, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/comments/index/add/:recruitment_id/:offset_time', to: 'comments#add_index', as: :comments_add, constraints: { recruitment_id:/[0-9]+/ }
  
  resources :chat_comments, only: [:destroy]
  get '/chat_comments/:recruitment_id', to: 'chat_comments#index', as: :chat_comments_index
  post '/chat_comments/create/:chat_id', to: 'chat_comments#create', as: :chat_comments_create

  resources :entry_chats, only: [:create, :destroy]
  # チャット有り結果選択
  get '/entry_chats/new/:recruitment_id', to: 'entry_chats#new', as: :new_entry_chats, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/entry_chats/new/add/:recruitment_id/:offset_time', to: 'entry_chats#add_result', as: :results_chat_add, constraints: { recruitment_id:/[0-9]+/ }

  root 'mains#index'

  get 'home/:acc_id', to: 'home#show', as: :account_show
  get '/home/button/:acc_id/:id', to: 'home#button', as: 'home_button'
  get 'home/delete/:acc_id', to: 'home#delete', as: :account_delete
  get '/home/button_view/:acc_id/:id', to: 'home#button_view', as: :home_button_view

  post '/' => 'tags#update'#タグ検索フォーム

  get '/mains/button_view/:id', to: 'mains#button_view', as: :mains_button_view
  get '/mains/button_form/:id', to: 'mains#button_form', as: :mains_button_form
  get '/mains/index/add/:size', to: 'mains#add_index', as: :mains_add, constraints: { size: /[0-9]+/ }

  get '/members/:chat_id', to: 'members#index', as: 'members'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/univtag/list', to: 'univtag#list' #タグ取得用

  get '/verify/recruit', to: 'verify#recruit' #検証用
  get '/verify/recruit2', to: 'verify#recruit2'
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  belongs_to :account
  has_many :comments, dependent: :destroy
  has_many :entry_chats, dependent: :destroy
  has_many :chat_comments, dependent: :destroy
  has_many :tagmaps, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :detail, presence: true
  validates :title, presence: true

  has_attached_file :photo,# styles: { medium: "300x300>"},
                    :url  =>"/assets/arts/:id/:style/:basename.:extension", # 画像保存先のURL先
                    :path => "#{Rails.root}/public/assets/arts/:id/:style/:basename.:extension" # サーバ上の画像保存先パス

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif","application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
                       #presence: true,  # ファイルの存在チェックはいらないはず
                       less_than: 5.megabytes# ファイルサイズのチェック


  # タグ名の配列からそのタグをすべて含む発言を取得する
  def self.tagnamesearch(tagname, limit, time, type)
    query = "SELECT recruitments.* FROM recruitments"
    if tagname.blank? then
      case type
      when 1 then #タイムライン
        com = Recruitment.where('updated_at < ?', time).order(updated_at: "DESC").limit(limit)
      when 2 then #発言
        com = Recruitment.where('updated_at < ?', time).where(re_id: '発言').order(updated_at: "DESC").limit(limit)
      when 3 then #募集
        com = Recruitment.where('updated_at < ?', time).where(re_id: '募集').where(resolved: '未解決').order(updated_at: "DESC").limit(limit)
      when 4 then #解決済み
        com = Recruitment.where('updated_at < ?', time).where(resolved: '解決').order(updated_at: "DESC").limit(limit)
      else
        com = nil
      end

    else
      cnt = 0
      for i in 0..(tagname.length)
        if tagname[i] != "" && tagname[i] != nil then
          tagquery = "SELECT  tags.* FROM tags WHERE tags.tag_name = \"" + tagname[i].encode("cp932", :invalid => :replace, :undef => :replace) + "\" LIMIT 1"
          tagid = Tag.find_by_sql([tagquery])
          joinand = " INNER JOIN tagmaps AS tag"+(i+1).to_s+" ON tag"+(i+1).to_s+".recruitment_id = recruitments.id AND tag"+(i+1).to_s+".tag_id = "
          if tagid.present? then
            query = query + joinand + tagid[0][:id].to_s
          else
            query = query + joinand + "NULL"
          end
          cnt += 1
        end
      end
      if cnt != 0 then
        case type
        when 1 then #タイムライン
          query = query + " WHERE recruitments.updated_at < \""+time+"\" ORDER BY recruitments.updated_at DESC LIMIT " + limit.to_s
        when 2 then #発言
          query = query + " WHERE recruitments.updated_at < \""+time+"\" AND recruitments.re_id = '発言' ORDER BY recruitments.updated_at DESC LIMIT " + limit.to_s
        when 3 then #募集
          query = query + " WHERE recruitments.updated_at < \""+time+"\" AND recruitments.re_id = '募集' AND recruitments.resolved = '未解決' ORDER BY recruitments.updated_at DESC LIMIT " + limit.to_s
        when 4 then #解決済み
          query = query + " WHERE recruitments.updated_at < \""+time+"\" AND recruitments.resolved = '解決' ORDER BY recruitments.updated_at DESC LIMIT " + limit.to_s
        else
          com = nil
        end
        com = Recruitment.find_by_sql([query])
        if com.blank? then
          com = Recruitment.none
        else
          com
        end
      else
        case type
        when 1 then #タイムライン
          com = Recruitment.where('updated_at < ?', time).order(updated_at: "DESC").limit(limit)
        when 2 then #発言
          com = Recruitment.where('updated_at < ?', time).where(re_id: '発言').order(updated_at: "DESC").limit(limit)
        when 3 then #募集
          com = Recruitment.where('updated_at < ?', time).where(re_id: '募集').where(resolved: '未解決').order(updated_at: "DESC").limit(limit)
        when 4 then #解決済み
          com = Recruitment.where('updated_at < ?', time).where(resolved: '解決').order(updated_at: "DESC").limit(limit)
        else
          com = nil
        end
      end
    end
    com
  end
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  before_action :set_recruitment, only: [ :edit, :add_result, :select, :selected, :destroy]
  before_action :add_answer, only: [:update]

  # GET /recruitments
  # GET /recruitments.json
  def index
    @recruitments = Recruitment.all
    @recruitments.order(updated_at: "DESC")
  end

  # GET /recruitments/1
  # GET /recruitments/1.json
  # チャット無しの結果選択表示
  def edit
    if @recruitment.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '募集が存在しません' }
        format.json { head :no_content }
      end
      return
    elsif !(account_signed_in? and @recruitment.acc_id == current_account.acc_id)
      respond_to do |format|
        format.html { redirect_to root_path, alert: '結果選択は募集者のみです' }
        format.json { head :no_content }
      end
      return
    end
    @comments = @recruitment.comments.limit(20) #20件を取得
  end

  #ajaxで動的に表示項目を追加する
  def add_result
    #ajax通信以外は弾く
    return redirect_to '/404.html' unless request.xhr?

    @comments = @recruitment.comments.where('updated_at > ?', Time.zone.parse(params[:offset_time])).limit(20)
  end

  # チャット無しの結果選択
  #ajaxで動的に選択
  def select
    #ajax通信以外は弾く
    return redirect_to '/404.html' unless request.xhr?

    if @recruitment.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '募集が存在しません' }
        format.json { head :no_content }
      end
    else
      @comment = Comment.find_by(id: params[:comment_id])
      @alert = nil
      @comment_id = params[:comment_id]
      if @comment.nil?
        @alert = '返信がありません'
      end
    end
  end

  # チャット無しの結果選択
  def selected
    #ajax通信以外は弾く
    return redirect_to '/404.html' unless request.xhr?

    if @recruitment.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '募集が存在しません' }
        format.json { head :no_content }
      end
    else
      @comment = Comment.find_by(id: params[:comment_id])
      @alert = nil
      @comment_id = params[:comment_id]
      if @comment.nil?
        @alert = '返信がありません'
      end
    end
  end

  # POST /recruitments
  # POST /recruitments.json
  def create

    @view_num = params[:view_num]
    @view_com_num = params[:id]
    @inputtag = Inputtag.new(inputtag_params)
    @inputtag.count_freetag

    @recruitment = Recruitment.new(recruitment_params)
    @recruitment.acc_id = current_account.acc_id#アカウントID
    @recruitment.account_id = current_account.id # アカウントの主キーのID 自動削除のため

    if @recruitment.detail.size ==0 || (@recruitment.detail.gsub(/\r\n|\r|\n|\s|\t/, "")).size==0
      @recruitment.detail = nil
    end

    if @view_com_num == '5'
      @recruitment.re_id  = '発言'
      @recruitment.title = "発言"
    else if  @view_com_num == '6'
           @recruitment.re_id  = '募集'
           @recruitment.resolved = '未解決'
         end
    end

    if @recruitment.photo_file_size != nil #ファイルがあった場合、file_idにurlを格納
      max_id = Recruitment.maximum(:id)
      if max_id.nil?
        @recruitment.file_id= "/assets/arts/1/original/" +@recruitment.photo_file_name
      else
        @recruitment.file_id= "/assets/arts/"+(max_id+1).to_s+"/original/" +@recruitment.photo_file_name
      end
    end

    if @recruitment.save
      #ファイル追加

      respond_to do |format|
        Tagmap.associate(@recruitment.id, @inputtag.tag_to_arry)
        if @recruitment.chat == "有"
          entry_chat = EntryChat.new(recruitment_id: @recruitment.id, account_id: @recruitment.account.id)
          entry_chat.save
        end
        format.html { redirect_to request_url(@inputtag.tag_to_arry, params[:view_num]), notice: '送信しました' }
        format.json { render :show, status: :created, location: @recruitment }
      end
    end
  end

  # PATCH/PUT /entry_chats/1
  # PATCH/PUT /entry_chats/1.json
  # 結果選択時のみ使用
  def update
    if @recruitment.chat == "有"
      if EntryChat.find_by(recruitment_id: @recruitment.id).nil?
        respond_to do |format|
          format.html { redirect_to new_entry_chats_path(@recruitment.id), alert: '結果を選択してください' }
          format.json { head :no_content }
        end
        return
      end
    elsif @recruitment.chat == "無"
      if @recruitment_params[:answer].blank?
        respond_to do |format|
          format.html { redirect_to edit_recruitment_path(@recruitment.id), alert: '結果を選択してください' }
          format.json { head :no_content }
        end
        return
      end
    end
    respond_to do |format|
      if @recruitment.update(@recruitment_params)
        format.html { redirect_to root_path, notice: '結果選択しました。募集を終了しました。' }
        format.json { render :show, status: :ok, location: @recruitment }
      else
        format.html { render :edit }
        format.json { render json: @recruitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruitments/1
  # DELETE /recruitments/1.json
  def destroy
    #ajax通信以外は弾く
    return redirect_to '/404.html' unless request.xhr?

    @alert = nil
    @recruitment_id = params[:id]

    if @recruitment.nil?
      @notice = 'すでに削除されています'
    else
      if @recruitment.destroy
        @notice = '削除されました'
      else
        @alert = '削除に失敗しました'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruitment
      @recruitment = Recruitment.find_by(id: params[:id])
    end

    def add_answer
      @recruitment = Recruitment.find(params[:id])
      @recruitment_params = { "resolved":"解決",
                              "answer":recruitment_params[:answer]}
      if @recruitment_params[:chat] == "有"
        @recruitment_params[:answer] = "募集は終了しました"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def recruitment_params
      params.require(:recruitment).permit(:acc_id, :resolved, :detail, :title, :answer, :file_id, :chat, :photo)
    end

    def inputtag_params
      params.permit(:school, :faculty, :department, :tag1, :tag2, :tag3, :tag4, :tag5, :tag6, :tag7, :tag8, :tag9, :tag10)
    end
    def arry_tag_params
      [params[:school],params[:faculty],params[:department],params[:tag1],params[:tag2],params[:tag3],params[:tag4],params[:tag5],params[:tag6],params[:tag7],params[:tag8],params[:tag9],params[:tag10]]
    end

    def request_url(tag,view_num)
      tag_url = "/?school="

      if tag[0].present? then
        tag_url = tag_url + tag[0]
      end
      tag_url = tag_url + "&faculty="
      if tag[1].present? then
        tag_url = tag_url + tag[1]
      end
      tag_url = tag_url + "&department="
      if tag[2].present? then
        tag_url = tag_url + tag[2]
      end

      for i in 1..10 do
        tag_url = tag_url + "&tag" + i.to_s + "="
        if tag[2 + i].present? then
          tag_url = tag_url + tag[2 + i]
        end
      end
      tag_url = tag_url + "&view_num="+view_num.to_s
      tag_url
    end
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/recruitments/_comment.html.erb
<div id=<%= "comment_" + comment.id.to_s %>>
<table width="100%" class="box_comment">
  <tr>
    <td class="box_comment2">
      <%= link_to account_show_path(comment.account.acc_id) do %>
        <%= comment.account.name %>
      <% end %>
    </td>
    <td class="box_comment2">
      <%= comment.account.acc_id %>
    </td>
    <td><%= comment.created_at %></td>
  </tr>
  <tr >
    <td colspan="3" class="box_comment3">
      <%= simple_format(comment.message) %>
    </td>
  </tr>
  <tr>
    <td colspan="3">
      <div id=<%= comment.id.to_s %> class="select">
        <%= render partial: 'recruitments/select', locals: {comment: comment} %>
      </div>
    </td>
  </tr>
</table>
</div>

app/views/recruitments/_decide_answer.html.erb
<%= form_with(model: recruitment, local: true) do |f| %>
  <%= f.hidden_field :answer, value: answer %>
  <%= f.submit "結果決定" %>
<% end %>

app/views/recruitments/_read_button.html.erb
<div >
  <% if last_comment.nil? %>
    <% if offset_time.nil? or offset_time == '0000-01-01 00:00:00' %>
      <!-- 返信が無い場合、もっと読み込むボタンは無し -->
      <%= button_to "更新", results_add_path(recruitment_id, '0000-01-01 00:00:00'), method: :post,
                    data: { disable_with: "処理中..." }, remote: true , class: "read_button"%>
    <% else %>
      <!-- 追加の返信がない場合-->
      <%= button_to "もっと読み込む", results_add_path(recruitment_id, offset_time), method: :post,
                    data: { disable_with: "処理中..." }, remote: true , class: "read_button"%>
    <% end %>
  <% else %>
    <%= button_to "もっと読み込む", results_add_path(recruitment_id, last_comment.updated_at.to_s), method: :post,
                  data: { disable_with: "処理中..." }, remote: true , class: "read_button"%>
  <% end %>
</div>

app/views/recruitments/_recruitment_form.html.erb
<div class="form_tabpanel">
  <%= render partial: 'mains/form', locals:{recruitment: recruitment, inputtag: inputtag, view_com_num: view_com_num, view_num: view_num}%>
</div>
<div class="form_tabpanel">
  <%= render partial: 'mains/form_r', locals:{recruitment: recruitment, inputtag: inputtag, view_com_num: view_com_num, view_num: view_num}%>
</div>

app/views/recruitments/_result.html.erb
<div class="result">
  <table border="2">
    <tr>
      <td>
          <%= result.account.name %>
      </td>
      <td><%= result.created_at %></td>
    </tr>
    <tr>
      <td colspan="2"><%= simple_format(result.message) %></td>
    </tr>
    <tr>
      <td colspan="2"><%= radio_button_tag :answer, result.message %></td>
    </tr>
  </table>
</div>

app/views/recruitments/_select.html.erb
<%= button_to "選択", select_result_path(comment.recruitment.id, comment.id),data: { disable_with: "処理中..." }, remote: true %>

app/views/recruitments/_selected.html.erb
<%= button_to "選択中", selected_result_path(comment.recruitment.id, comment.id),data: { disable_with: "処理中..." }, remote: true %>

app/views/recruitments/add_result.js.erb
$('#add_results').append(
    "<%= escape_javascript(render partial: "recruitments/comment", collection: @comments) %>"
);
$('#request_add_results').html(
    "<%=escape_javascript(render partial: 'recruitments/read_button',
    locals: {recruitment_id: params[:id], last_comment:@comments.last, offset_time: params[:offset_time]})%>"
);

app/views/recruitments/create.js.erb
$('#recruitment_error').html("<%=escape_javascript(render partial: 'recruitments/recruitment_error', locals: {recruitment: @recruitment}) %>")
$('.form_tabpanels').html("<%=escape_javascript(render partial: 'recruitments/recruitment_form',
locals: {recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num})%>")

app/views/recruitments/destroy.js.erb
<% if @alert.nil? %>
$('<%= "#recruitment_" + @recruitment_id.to_s %>').remove();
$('#flash_message').html("<%=escape_javascript(render partial: 'layouts/flash_message', locals: {notice: @notice}) %>");
<% else %>
$('#flash_message').html("<%=escape_javascript(render partial: 'layouts/flash_message', locals: {alert: @alert}) %>");
<% end %>

app/views/recruitments/edit.html.erb
<!-- 16t4032n 田中裕隆 -->
<h2>結果選択</h2>

<table width="100%">
  <tr>
    <td>
      <%= render partial: 'comments/recruitment', locals: {recruitment: @recruitment} %>
    </td>
  </tr>

  <tr>
    <td>
      <table class="box3">
        <tr>
          <td>
            <div id="add_results">
              <%= render partial: "comment", collection: @comments %>
            </div>
            <table width="100%">
              <tr>
                <td>
                  <div id="request_add_results">
                    <%= render partial: 'recruitments/read_button', locals: {recruitment_id: params[:id], last_comment: @comments.last, offset_time: nil } %>
                  </div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <tr>
    <td>
      <div id="decide_answer">
        <%= render partial: 'recruitments/decide_answer', locals: {recruitment: @recruitment, answer: nil} %>
      </div>
    </td>
  </tr>

</table>

app/views/recruitments/select.js.erb
<% if @alert.nil? %>
$('#decide_answer').html(
    "<%=escape_javascript(render partial: 'recruitments/decide_answer', locals: {recruitment: @recruitment, answer: @comment.message})%>"
);
var selected_id = $('.selected').attr("id")
$('.selected').html("<form class=\"button_to\" method=\"post\" action=\"/recruitments/select/"+ "<%=escape_javascript(@recruitment.id.to_s)%>" +"/"+ selected_id +"\" data-remote=\"true\"><input data-disable-with=\"処理中...\" class=\"select\" type=\"submit\" value=\"選択\"></form>")
$('<%= "#" + @comment.id.to_s %>').html(
    "<%= escape_javascript(render partial: 'recruitments/selected', locals: {comment: @comment}) %>"
);
$('<%= "#" + @comment.id.to_s %>').attr(
    "class", "selected"
)
<% else %>
$('<%= "#comment_" + @comment_id.to_s %>').remove();
$('#flash_message').html("<%=escape_javascript(render partial: 'layouts/flash_message', locals: {alert: @alert}) %>");
<% end %>

app/views/recruitments/selected.js.erb
<% if @alert.nil? %>
$('#decide_answer').html(
    "<%=escape_javascript(render partial: 'recruitments/decide_answer', locals: {recruitment: @recruitment, answer: ''})%>"
);
$('<%= "#" + @comment.id.to_s %>').html(
    "<%= escape_javascript(render partial: 'recruitments/select', locals: {comment: @comment}) %>"
);
$('.selected').attr("class", "select");
<% else %>
$('<%= "#comment_" + @comment_id.to_s %>').remove();
$('#flash_message').html("<%=escape_javascript(render partial: 'layouts/flash_message', locals: {alert: @alert}) %>");
<% end %>

app/views/recruitments/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '戻る', '/' %>
<p>
  <!-- 追加箇所 開始-->
<p>
  <strong>ファイルは以下のリンクから参照できます:</strong>
  <!--- Modelのstyleで指定した :midium など渡すことでサイズを指定できる -->
  <%= link_to 'ファイルを表示する', @recruitment.file_id%>
</p>
<!-- 追加箇所 終了-->