config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks, only: [:create, :destroy]

  devise_for :accounts, :controllers =>{
      :registrations => 'accounts/registrations'
  }

  devise_scope :account do
    post '/accounts/sign_up/confirm', to: 'accounts/registrations#confirm'
    delete '/accounts/:id', to: 'accounts/registrations#destroy', as: :account_destroy, constraints: {id: /[0-9]+/ }
  end

  resources :recruitments, only: [ :edit, :update, :destroy ]
  post '/recruitments/create/:id', to: 'recruitments#create', as: :recruitments_create
  post '/recruitments/:id', to: 'recruitments#update', constraints: {id: /[0-9]+/ }
  # 返信追加読み込み
  post '/recruitments/edit/add/:id/:offset_time', to: 'recruitments#add_result', as: :results_add, constraints: { id:/[0-9]+/ }
  post '/recruitments/select/:id/:comment_id', to: 'recruitments#select', as: :select_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }
  post '/recruitments/selected/:id/:comment_id', to: 'recruitments#selected', as: :selected_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }

# 返信生成削除
  resources :comments, only: [ :create, :destroy ]
  get '/comments/index/:recruitment_id', to: 'comments#index', as: :comments_index, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/comments/index/add/:recruitment_id/:offset_time', to: 'comments#add_index', as: :comments_add, constraints: { recruitment_id:/[0-9]+/ }
  
  resources :chat_comments, only: [:destroy]
  get '/chat_comments/:recruitment_id', to: 'chat_comments#index', as: :chat_comments_index
  post '/chat_comments/create/:chat_id', to: 'chat_comments#create', as: :chat_comments_create

  resources :entry_chats, only: [:create, :destroy]
  # チャット有り結果選択
  get '/entry_chats/new/:recruitment_id', to: 'entry_chats#new', as: :new_entry_chats, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/entry_chats/new/add/:recruitment_id/:offset_time', to: 'entry_chats#add_result', as: :results_chat_add, constraints: { recruitment_id:/[0-9]+/ }

  root 'mains#index'

  get 'home/:acc_id', to: 'home#show', as: :account_show
  get '/home/button/:acc_id/:id', to: 'home#button', as: 'home_button'
  get 'home/delete/:acc_id', to: 'home#delete', as: :account_delete
  get '/home/button_view/:acc_id/:id', to: 'home#button_view', as: :home_button_view

  post '/' => 'tags#update'#タグ検索フォーム

  get '/mains/button_view/:id', to: 'mains#button_view', as: :mains_button_view
  get '/mains/button_form/:id', to: 'mains#button_form', as: :mains_button_form
  get '/mains/index/add/:size', to: 'mains#add_index', as: :mains_add, constraints: { size: /[0-9]+/ }

  get '/members/:chat_id', to: 'members#index', as: 'members'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/univtag/list', to: 'univtag#list' #タグ取得用

  get '/verify/recruit', to: 'verify#recruit' #検証用
  get '/verify/recruit2', to: 'verify#recruit2'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # アカウント情報画面
  def show

    @home_button = '1'
    @view_num = '1'
    @account = Account.find_by(acc_id: params[:acc_id])
    @bookmark = Bookmark.new
    if @account.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '存在しないアカウントです' }
        format.json { head :no_content }
      end
    else
      @recruitments = @account.recruitments.order(updated_at: "DESC")
      @entry_chats = @account.entry_chats
    end
  end


  # アカウント削除画面
  def delete
    @account = Account.find_by(acc_id: params[:acc_id])
    if @account.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '存在しないアカウントです' }
        format.json { head :no_content }
      end
    elsif @account.id != current_account.id and current_account.acc_id != 'administrator'
      respond_to do |format|
        format.html { redirect_to root_path, alert: '削除権限がありません' }
        format.json { head :no_content }
      end
    end
  end

  def button
    @home_button = params[:id]
    @view_num = '1'
    @account = Account.find_by(acc_id: params[:acc_id])
    @bookmark = Bookmark.new
    if @account.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '存在しないアカウントです' }
        format.json { head :no_content }
      end
    else
      if @home_button == '1'
      @recruitments = @account.recruitments.order(updated_at: "DESC")
      elsif @home_button == '2'
        @recruitments = @account.bookmark_recruitments
      elsif @home_button == '3'
        @entry_chats = @account.entry_chats
      end

      render template: 'home/show'
    end
  end

  def button_view
    @account = Account.find_by(acc_id: params[:acc_id])
    @view_num = params[:id]
    @bookmark = Bookmark.new
    if @view_num == '1'
      @recruitments = @account.recruitments.order(updated_at: "DESC")                         #タイムライン
    elsif @view_num == '2'
      @recruitments = @account.recruitments.where(re_id: '発言').order(updated_at: "DESC")    #発言
    elsif @view_num == '3'
      @recruitments = @account.recruitments.where(resolved: '未解決').order(updated_at: "DESC") #募集
    elsif @view_num == '4'
      @recruitments = @account.recruitments.where(resolved: '解決').order(updated_at: "DESC") #解決済み募集
    end
  end

end

app/views/home/_button.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<div class="button">
  <table  align="left" ><tr><td>
    <% if @home_button == '1' %>
      <div class="on">
        <%= button_to '自身のコメント', home_button_path(acc_id,'1'), method: :get, disabled: :disabled %>
      </div>
    <% else %>
      <%= button_to '自身のコメント', home_button_path(acc_id, '1'), method: :get %>
    <% end %>
  </td></tr></table>
  <table class="button" align="left"><tr><td>
    <% if @home_button == '2' %>
      <div class="on">
        <%= button_to 'ブックマーク', home_button_path(acc_id, '2'), method: :get, disabled: :disabled %>
      </div>
    <% else %>
      <%= button_to 'ブックマーク', home_button_path(acc_id, '2'), method: :get %>
    <% end %>
  </td></tr></table>
  <table class="button" align="left"><tr><td>
    <% if @home_button == '3' %>
      <div class="on">
        <%= button_to '参加中のチャット一覧', home_button_path(acc_id, '3'), method: :get, disabled: :disabled %>
      </div>
    <% else %>
      <%= button_to '参加中のチャット一覧', home_button_path(acc_id, '3'), method: :get %>
    <% end %>
  </td></tr></table>
</div>
<br>

app/views/home/_button_v.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<div class ="box1">
<div class="button1">
  <% if view_num == '1' %>
    <%= button_to 'タイムライン', home_button_view_path(acc_id, 1), method: :get, disabled: :disabled ,remote: true%>
  <% else %>
    <span class="on">
      <%= button_to 'タイムライン', home_button_view_path(acc_id, 1), method: :get, remote: true %>
    </span>
  <% end %>
  <% if view_num == '2' %>
    <%= button_to '発言', home_button_view_path(acc_id, 2), method: :get, disabled: :disabled ,remote: true %>
  <% else %>
    <span class="on">
      <%= button_to '発言', home_button_view_path(acc_id, 2), method: :get, remote: true %>
    </span>
  <% end %>
  <% if view_num == '3' %>
    <%= button_to '募集', home_button_view_path(acc_id, 3), method: :get, disabled: :disabled ,remote: true %>
  <% else %>
    <span class="on">
      <%= button_to '募集', home_button_view_path(acc_id, 3), method: :get, remote: true %>
    </span>
  <% end %>
  <% if view_num == '4' %>
    <%= button_to '募集解決済み', home_button_view_path(acc_id, 4), method: :get, disabled: :disabled ,remote: true %>
  <% else %>
    <span class="on">
      <%= button_to '募集解決済み', home_button_view_path(acc_id, 4), method: :get, remote: true %>
    </span>
  <% end %>
</div>
</div>

app/views/home/_view.html.erb
<table>
  <% @recruitments.order("updated_at DESC").each do |recruitment| %>
    <div class="box">
      <% if recruitment.re_id == '募集'%>
        <div><%= recruitment.title %></div>
      <% end %>
      <span><%= recruitment.created_at %></span>
      <span><%= link_to account_show_path(recruitment.acc_id) do %>
         <%= Account.find_by(acc_id: recruitment.acc_id).name %>
        <% end %>
         </span>
      <span>
      <%= link_to '返信📨', comments_index_path(recruitment.id), method: :get  %>
        </span>
      <span>
        <% if account_signed_in? %>
          <% if current_account.acc_id == recruitment.acc_id %>
            <% if recruitment.re_id == '募集'%>
              <% if  recruitment.resolved == '未解決' %>
                <% if recruitment.chat == "有" %>
                  <%= link_to '募集結果選択', new_entry_chats_path(recruitment.id), method: :get  %>
                <% elsif recruitment.chat == "無" %>
                  <%= link_to '募集結果選択', edit_recruitment_path(recruitment.id), method: :get  %>
                <% end %>
              <% elsif recruitment.resolved == '解決' && recruitment.chat == "有" && (current_account.acc_id == recruitment.acc_id || EntryChat.where(chat: recruitment.id).find(acc_id: current_account.acc_id).present?) %>
                <span>
                  <%= link_to 'チャット', chat_comments_index_path(recruitment.id), method: :get  %>
                </span>
              <% end %>
            <% end %>
            <%= link_to '削除🚮', recruitment, method: :delete, data: { confirm: '削除しますか?' } %>
          <%end %>
        <% end %>
        </span>
      <div><%= recruitment.detail %></div>
      <br>
    </div>
  <% end %>
</table>

app/views/home/_view_c.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<p id="notice"><%= notice %></p>
  <% entry_chats.each do |entry_chat| %>
    <table width="100%"  class="box_comment">
      <% if entry_chat.recruitment.resolved == "解決" %>
        <tr>
          <td class="box-title" colspan="2"><%= entry_chat.recruitment.title %></td>
          <td>
            <div class="button1">
              <div class="on">
                <%= button_to 'チャットへ💭', chat_comments_index_path(entry_chat.recruitment.id), method: :get %>
              </div>
            </div>
          </td>
        </tr>
        <td class="box_comment3"><%= entry_chat.recruitment.detail  %></td>
      <% end %>
    </table>
<% end %>

app/views/home/button_view.js.erb
$('#button_v2').html(
    "<%= escape_javascript render 'home/button_v', view_num: @view_num, acc_id: @account.acc_id %>"
);
$('#button_v3').html(
    "<%=
    if @view_num == '1'
    escape_javascript render 'mains/view_t', recruitments: @recruitments
    elsif @view_num == '2'
    escape_javascript render 'mains/view_t', recruitments: @recruitments
    elsif @view_num == '3'
    escape_javascript render 'mains/view_t', recruitments: @recruitments
    elsif @view_num == '4'
    escape_javascript render 'mains/view_t', recruitments: @recruitments
    end
    %>"
);

app/views/home/delete.html.erb
<h2>アカウント削除</h2>

<p>削除ボタンを押すと、あなたのアカウントは削除されます。<br />
  アカウントを削除すると、発言など全ての情報が削除されます。<br />
  アカウントを削除した後、削除する前に戻すことはできません。<br />
  <%= button_to "削除", account_destroy_path(@account.id), data: { confirm: "本当にアカウントを削除しますか？" }, method: :delete %></p>

<%= link_to "戻る", :back %>

app/views/home/show.html.erb
<h2> アカウント情報 </h2>
<div  id="account_info_space">
  <table width="100%">
    <tr>
      <td width="50%" style="padding: 17px 0 0 4px;">
        <div class="account_info_content">
          <table>
            <tr>
              <td width="80px">アカウント名</td>
              <td><%= @account.name %></td>
            </tr>
            <tr>
              <td width="80px">ID</td>
              <td><%= @account.acc_id %><td>
            </tr>
          </table>
        </div>
      </td>
      <td rowspan="2">
        <p class="account_info_index">所属</p>
        <div class="account_info_content">
          <table>
            <tr>
              <td width="40px">大学</td>
              <td><%= @account.university %></td>
            </tr>
            <tr>
              <td width="40px">学部</td>
              <td><%= @account.faculty %><td>
            </tr>
            <tr>
              <td width="40px">学科</td>
              <td><%= @account.department %><td>
            </tr>
            <tr>
              <td width="40px">学年</td>
              <td><%= @account.grade %><td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
    <tr>
      <td height="25px">
        <% if account_signed_in? %>
          <% if current_account.id == @account.id or current_account.acc_id == 'administrator' %>
            <table width="100%">
              <tr>
                <% if current_account.acc_id != 'administrator' %>
                  <td style="padding-left: 20px">
                    <%= button_to "アカウント情報更新", edit_account_registration_path , method: :get%>
                  </td>
                <% end %>
                <td>
                  <%= button_to "アカウント削除", account_delete_path(@account.acc_id) , method: :get%>
                </td>
              </tr>
            </table>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
  <p class="account_info_index">紹介文</p>
  <div class="account_info_content" id="account_info_content-intro">
    <%= simple_format(@account.introduction) %>
  </div>
</div>

<br>
  <div>
    <%= render 'button', acc_id: @account.acc_id %>
  </div>
<br>
<br>
<% if @home_button == '1' %>
    <div id="button_v2">
      <%= render 'home/button_v', view_num: @view_num, acc_id: @account.acc_id %>
    </div>
  <div class="box3" id="button_v3">
    <%= render 'mains/view_t', recruitments: @recruitments %>  <!--個人の発言-->
  </div>
<% elsif @home_button == '2' %>
  <%= render 'mains/view_t',recruitment: @recruitments %> <!--ブックマーク-->
<% elsif @home_button == '3' %>
  <%= render 'view_c',entry_chats: @entry_chats %> <!--チャット一覧-->
<% end %>