config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks, only: [:create, :destroy]

  devise_for :accounts, :controllers =>{
      :registrations => 'accounts/registrations'
  }

  devise_scope :account do
    post '/accounts/sign_up/confirm', to: 'accounts/registrations#confirm'
    delete '/accounts/:id', to: 'accounts/registrations#destroy', as: :account_destroy, constraints: {id: /[0-9]+/ }
  end

  resources :recruitments, only: [ :edit, :update, :destroy ]
  post '/recruitments/create/:id', to: 'recruitments#create', as: :recruitments_create
  post '/recruitments/:id', to: 'recruitments#update', constraints: {id: /[0-9]+/ }
  # 返信追加読み込み
  post '/recruitments/edit/add/:id/:offset_time', to: 'recruitments#add_result', as: :results_add, constraints: { id:/[0-9]+/ }
  post '/recruitments/select/:id/:comment_id', to: 'recruitments#select', as: :select_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }
  post '/recruitments/selected/:id/:comment_id', to: 'recruitments#selected', as: :selected_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }

# 返信生成削除
  resources :comments, only: [ :create, :destroy ]
  get '/comments/index/:recruitment_id', to: 'comments#index', as: :comments_index, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/comments/index/add/:recruitment_id/:offset_time', to: 'comments#add_index', as: :comments_add, constraints: { recruitment_id:/[0-9]+/ }
  
  resources :chat_comments, only: [:destroy]
  get '/chat_comments/:recruitment_id', to: 'chat_comments#index', as: :chat_comments_index
  post '/chat_comments/create/:chat_id', to: 'chat_comments#create', as: :chat_comments_create

  resources :entry_chats, only: [:create, :destroy]
  # チャット有り結果選択
  get '/entry_chats/new/:recruitment_id', to: 'entry_chats#new', as: :new_entry_chats, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/entry_chats/new/add/:recruitment_id/:offset_time', to: 'entry_chats#add_result', as: :results_chat_add, constraints: { recruitment_id:/[0-9]+/ }

  root 'mains#index'

  get 'home/:acc_id', to: 'home#show', as: :account_show
  get '/home/button/:acc_id/:id', to: 'home#button', as: 'home_button'
  get 'home/delete/:acc_id', to: 'home#delete', as: :account_delete
  get '/home/button_view/:acc_id/:id', to: 'home#button_view', as: :home_button_view

  post '/' => 'tags#update'#タグ検索フォーム

  get '/mains/button_view/:id', to: 'mains#button_view', as: :mains_button_view
  get '/mains/button_form/:id', to: 'mains#button_form', as: :mains_button_form
  get '/mains/index/add/:size', to: 'mains#add_index', as: :mains_add, constraints: { size: /[0-9]+/ }

  get '/members/:chat_id', to: 'members#index', as: 'members'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/univtag/list', to: 'univtag#list' #タグ取得用

  get '/verify/recruit', to: 'verify#recruit' #検証用
  get '/verify/recruit2', to: 'verify#recruit2'
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

  def index
    if params.has_key?(:view_num) then
      @view_num = params[:view_num]
    else
      @view_num = '1'
    end

    @view_com_num = '5'
    @bookmark = Bookmark.new

    @recruitment = Recruitment.new

    if account_signed_in? then #ログインしている
      @taghistoryid = Taghistoryid.new #履歴用に変数準備
      if params.has_key?(:school) then #パラメータを受け取っている
        @inputtag = Inputtag.new(inputtag_params) #入力されているタグを取得
        @inputtag.freetagnum = @inputtag.count_freetag
        @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2, DateTime.tomorrow.to_s, @view_num.to_i) #入力されているタグで検索
      else #パラメータを受け取っていない
        @inputtag = Inputtag.new
        if current_account.id != 1 then
          @inputtag.setuniv(school: current_account.university, faculty: current_account.faculty, department: current_account.department) #タグに大学情報セット
        end
        @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2, DateTime.tomorrow.to_s, 1)
      end
    else #ログインしていない
      if params.has_key?(:school) then #パラメータを受け取っている
        @inputtag = Inputtag.new(inputtag_params) #入力されているタグを取得
        @inputtag.freetagnum = @inputtag.count_freetag
        @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2, DateTime.tomorrow.to_s, @view_num.to_i) #入力されているタグで検索
      else
        @inputtag = Inputtag.new
        @recruitments = Recruitment.tagnamesearch([],2, DateTime.tomorrow.to_s, 1)
      end
    end

    render template: 'mains/add_index'
  end

  def add_index
    @inputtag = Inputtag.new
    @view_num = params[:view_num]
    if params.has_key?(:school) then #パラメータを受け取っている
      @inputtag = Inputtag.new(inputtag_params)
      @inputtag.freetagnum = @inputtag.count_freetag
      @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2, params[:oldest], @view_num.to_i) #入力されているタグで検索
      logger.debug("検索")
    end
    logger.debug(params[:oldest])
    if @recruitments.present? then
      @oldest = @recruitments.last.updated_at.utc.to_s
    else
      @oldest = params[:oldest].to_time
    end
  end

  def button_view
    @inputtag = Inputtag.new(inputtag_params)#入力されているタグを取得

    @inputtag.freetagnum = @inputtag.count_freetag
    if account_signed_in? then #ログインしている
      @taghistoryid = Taghistoryid.new
    end
    @view_num = params[:id]
    if @view_num == '1'
      @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2,DateTime.tomorrow.to_s,1) #タイムライン
    elsif @view_num == '2'
      @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2,DateTime.tomorrow.to_s,2) #発言
    elsif @view_num == '3'
      @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2,DateTime.tomorrow.to_s,3) #募集
    elsif @view_num == '4'
      @recruitments = Recruitment.tagnamesearch(@inputtag.tag_to_arry,2,DateTime.tomorrow.to_s,4) #解決済み募集
    end
  end

  def button_form
    @view_num =params[:view_num]
    @bookmark = Bookmark.new

    @recruitment = Recruitment.new
    @inputtag = Inputtag.new(inputtag_params)#入力されているタグを取得

    @inputtag.freetagnum = @inputtag.count_freetag

    if account_signed_in? then #ログインしている
      @taghistoryid = Taghistoryid.new
    end

      @view_com_num = params[:id]

    if account_signed_in? then
      @inputtag.setuniv school: current_account.university, faculty: current_account.faculty, department: current_account.department
    end
  end



  #タグ検索フォームの情報を取得する
  def inputtag_params
    params.permit(:school, :faculty, :department, :tag1, :tag2, :tag3, :tag4, :tag5, :tag6, :tag7, :tag8, :tag9, :tag10)
  end

end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/_button_f.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<div class="button1">
<table ><tr><td>
  <% if view_com_num == '5' %>
    <%= button_to '発言', mains_button_form_path(5), method: :get, disabled: :disabled ,remote: true%>
  <% else %>
     <span class="on">
    <%= button_to '発言', mains_button_form_path(5), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10,view_num:@view_num}, remote: true%>
     </span>
  <% end %>
</td>
<td>
  <% if view_com_num == '6' %>
    <%= button_to '募集', mains_button_form_path(6), method: :get, disabled: :disabled ,remote: true%>
  <% else %>
     <span class="on">
    <%= button_to '募集', mains_button_form_path(6), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10,view_num:@view_num}, remote: true %>
     </span>
  <% end %>
</td></tr></table>
</div>

app/views/mains/_community.html.erb
<h2>コミュニティ選択窓予定地</h2>
<div></div>

app/views/mains/_form.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<!--======================発言フォーム==========================-->
<%= form_with(model: recruitment, url: recruitments_create_path(5)) do |form| %>

  <div class="form_layout">
    <div style="padding: 0px" class="form_layout_item-textarea">
      <div style="height: 80px"><%= form.text_area :detail,maxlength:"1000", placeholder: "本文を入力して下さい", id: "talk_input_form"%></div>
      <div><label for="talk_input_file" id="talk_input_file_label-label"><span id="talk_input_file_label">ファイルを選択して下さい</span>
        <%= form.file_field :photo, id: "talk_input_file" %>
      </label></div>
    </div>

    <div class="form_layout_item-submit">
       <!--<div class="actions">-->
        <!--====================タグ検索情報====================-->
        <input type="hidden" name="school" value="<%=@inputtag.school %>">
        <input type="hidden" name="faculty" value="<%=@inputtag.faculty %>">
        <input type="hidden" name="department" value="<%=@inputtag.department %>">
        <input type="hidden" name="tag1" value="<%=@inputtag.tag1 %>">
        <input type="hidden" name="tag2" value="<%=@inputtag.tag2 %>">
        <input type="hidden" name="tag3" value="<%=@inputtag.tag3 %>">
        <input type="hidden" name="tag4" value="<%=@inputtag.tag4 %>">
        <input type="hidden" name="tag5" value="<%=@inputtag.tag5 %>">
        <input type="hidden" name="tag6" value="<%=@inputtag.tag6 %>">
        <input type="hidden" name="tag7" value="<%=@inputtag.tag7 %>">
        <input type="hidden" name="tag8" value="<%=@inputtag.tag8 %>">
        <input type="hidden" name="tag9" value="<%=@inputtag.tag9 %>">
        <input type="hidden" name="tag10" value="<%=@inputtag.tag10 %>">
        <input type="hidden" name="view_num" value="<%=@view_num %>">
        <!--====================タグ検索情報====================-->
        <!--<div class="button1">-->
        <!--<div class="on">-->
        <%= form.submit"送信📤", id: "talk_input_form_submit"%>

      <!--</div>-->
    </div>
  </div>
<% end %>


<script>
    var file_slect = document.getElementById('talk_input_file');
    file_slect.addEventListener('change',function(){
        document.getElementById("talk_input_file_label").textContent=this.value;
    },false);

    if(document.getElementById("talk_input_file_label-label").lastElementChild.className=='field_with_errors'){
        document.getElementById("talk_input_file_label-label").style.borderColor = '#ff0847'
        document.getElementById("talk_input_file_label-label").style.backgroundColor = '#ffebeb'
    }
</script>

app/views/mains/_form_change.html.erb
<!--
発言と募集フォームの切り替え
-->
<div class="form_tab">
  <input type="radio" name="form_tab" id="form_tab_1" aria-controls="first_tab02" checked>
  <label for="form_tab_1">発言</label>
  <input type="radio" name="form_tab" id="form_tab_2" aria-controls="second_tab02">
  <label for="form_tab_2">募集</label>
  <div class="form_tabpanels">
    <%= render 'recruitments/recruitment_form', recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num %>
  </div>
</div>

app/views/mains/_view_t.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
  <% @recruitments.each do |recruitment| %>

    <div id=<%="recruitment_" + recruitment.id.to_s %>>
      <table width="100%"  class="box_comment">
        <tr>

          <td>
            <table width="100%">
              <tr>
                <td class="box_comment2">
                  <%= link_to account_show_path(recruitment.account.acc_id) do %>
                    <%= recruitment.account.name %>👤
                  <% end %>
                </td>
                <td class="box_comment2">
                  <%= recruitment.account.acc_id %>
                </td>
                <td class="box_comment2">
                  <%= recruitment.created_at %>
                </td>
              </tr>
              <% if recruitment.re_id == '募集'%>
                <tr>
                  <td class="box-title" colspan="2">
                    <%= recruitment.title %>
                  </td>
                  <td class="box_comment2">
                    (チャット<%= recruitment.chat %>)
                  </td>
                </tr>
              <% end %>
              <tr>
                <td class="box_comment3" colspan="3">
                  <%= simple_format(recruitment.detail) %>
                </td>
              </tr>
              <%if recruitment.photo_file_size  != nil%>
                <tr>
                  <td class="box_comment3" colspan="3">
                    <%= link_to 'ファイルを表示する', recruitment.file_id %>
                  </td>
                </tr>
              <%end %>

              <% if recruitment.resolved == '解決' %>
                <tr>
                  <td colspan="3">
                    <div class="box_comment4">
                      <div class="box-title">
                        回答🔍
                      </div>
                      <%= simple_format(recruitment.answer) %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </table>
          </td>
        </tr>

        <tr>
          <td>
            <table width="100%">
              <tr>
                <td >
                  <%= button_to '返信📨', comments_index_path(recruitment.id), method: :get  %>
                </td>
                <% if account_signed_in? %>
                  <td>

                    <%= render partial: 'bookmarks/bookmark', locals: { current_account_id: current_account.id, recruitment_id: recruitment.id} %>
                  </td>

                  <% if current_account.acc_id == recruitment.acc_id %>
                    <% if recruitment.re_id == '募集'%>
                      <td>
                        <% if  recruitment.resolved == '未解決' %>
                          <% if recruitment.chat == "有" %>
                            <%= button_to '募集結果選択☝', new_entry_chats_path(recruitment.id), method: :get  %>
                          <% elsif recruitment.chat == "無" %>
                            <%= button_to '募集結果選択☝', edit_recruitment_path(recruitment.id), method: :get  %>
                          <% end %>
                        <% elsif recruitment.resolved == '解決' && recruitment.chat == "有" %>
                          <%= button_to 'チャット💭', chat_comments_index_path(recruitment.id), method: :get  %>
                        <% end %>
                      </td>
                    <%end %>
                    <td >
                      <%= button_to '削除🚮', recruitment, method: :delete, data: { confirm: '削除しますか?' }, remote: true %>
                    </td>
                  <% elsif current_account.acc_id == 'administrator' %>
                    <% if recruitment.resolved == '解決' && recruitment.chat == "有" %>
                      <td>
                        <%= button_to 'チャット💭', chat_comments_index_path(recruitment.id), method: :get %>
                      </td>
                    <% end %>
                    <td>
                      <%= button_to '削除🚮', recruitment, method: :delete , data: { confirm: '削除しますか?' }, remote: true %>
                    </td>
                  <% elsif  EntryChat.where(chat_id: recruitment.id).find_by(acc_id: current_account.acc_id).present? %>
                    <td>
                      <%= button_to 'チャット💭', chat_comments_index_path(recruitment.id), method: :get  %>
                    </td>
                  <%end %>
                <% end %>
              </tr>
            </table>
          </td>
        </tr>

      </table>
    </div>
  <% end %>

app/views/mains/add_index.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>

<div>
  <%= render :partial =>'tags/form' , inputtag: @inputtag , taghistoryid: @taghistoryid, view_num: @view_num%>
</div>

<% if account_signed_in? %><!--入力フォーム-->
  <div id="recruitment_error">
    <!-- ここにエラーを表示する -->
  </div>
  <%= render partial: 'mains/form_change', recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num%>
<% end %>

<div id="button_v2">
  <%= render 'mains/button_v', view_num: @view_num %>
</div>

<br>
<br>

<div class="button1">
  <div class="on">
    <div id="button_v">
      <%= button_to '最新を読み込む', mains_button_view_path(@view_num), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10,view_num:@view_num}, remote: true %>
    </div>
  </div>
</div>



<br>
<br>
<div class="box3" id="button_v3">
  <%= render 'mains/view_t', recruitments: @recruitments %>
</div>

<div class="button1">
  <div class="on">
<div id="button_v4">
  <% if @recruitments.present? then %>
    <%=button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:@recruitments.last.updated_at.utc.to_s, view_num: @view_num}, remote: true %>
  <% else %>
    <%=button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:DateTime.tomorrow , view_num: @view_num}, remote: true %>
  <% end %>
</div>
  </div>
</div>
</span>

app/views/mains/add_index.js.erb
$('#button_v3').append(
    "<%=
    escape_javascript(render 'mains/view_t', recruitments: @recruitments)
    %>"
);
$('#button_v4').html(
    "<%=
      escape_javascript button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:@oldest, view_num: @view_num}, remote: true
    %>"
);

app/views/mains/button_form.js.erb
$('#button_f').html(
    "<%=
    escape_javascript render 'mains/button_f', recruitment: @recruitment, view_com_num: @view_com_num, view_num: @view_num
   %>"
);
$('#button_f2').html(
    "<%=
    if @view_com_num == '5'
     escape_javascript render partial: 'mains/form', locals:{recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num}
     elsif @view_com_num == '6'
     escape_javascript render partial: 'mains/form_r', locals:{recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num}
    end %>"
);

app/views/mains/button_view.js.erb
$('#button_v').html(
    "<%=
    escape_javascript button_to '最新を読み込む', mains_button_view_path(@view_num), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, viewnum: @view_num}, data: {disable_with:""},remote: true%>"
);
$('#button_v2').html(
    "<%= escape_javascript render 'mains/button_v', view_num: @view_num%>"
);
$('#button_v3').html(
    "<%=
    escape_javascript render 'mains/view_t', recruitments: @recruitments
    %>"
);
$('#button_v4').html(
    "<%=
    if @recruitments.present? then
      escape_javascript button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:@recruitments.last.updated_at.utc.to_s, view_num: @view_num}, remote: true
    else
      escape_javascript button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:DateTime.tomorrow , view_num: @view_num}, remote: true
    end
    %>"
);

app/views/mains/index.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<!--<%= render 'devise/shared/accounts_accessor' %>-->

<div>
    <%= render :partial =>'tags/form' , inputtag: @inputtag , taghistoryid: @taghistoryid, view_num: @view_num%>
</div>
<br>
<% if account_signed_in? %>
<div id = "button_f">
    <%= render 'mains/button_f', recruitment: @recruitment, view_com_num: @view_com_num, view_num: @view_num%>
</div>
<br>
<div id = "button_f2">

  <div id="recruitment_form">
    <%= render 'recruitments/recruitment_form', recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num, view_num: @view_num %>
  </div>
</div>
<% end %>
<div class="button1">
    <div class="on">
        <div id="button_v">
            <%= button_to '最新を読み込む', mains_button_view_path(@view_num), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10,view_num:@view_num}, remote: true %>
        </div>
    </div>
</div>
<br>

<div id="button_v2">
    <%= render 'mains/button_v', view_num: @view_num %>
</div>
<br>
<br>
<div class="box3" id="button_v3">
    <%= render 'mains/view_t', recruitments: @recruitments %>
</div>

<div class="button1">
  <div class="on">
    <div id="button_v4">
      <% if @recruitments.present? %>
        <%= button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10, oldest:@recruitments.last.updated_at.to_s, viewnum: @view_num}, remote: true %>
      <% end %>
    </div>
  </div>
</div>
</span>

app/views/mains/index_f.html.erb
<%= stylesheet_link_tag "box.css", :media => "all" %>
<!--<%= render 'devise/shared/accounts_accessor' %>-->

<div>
  <%= render :partial =>'tags/form' , inputtag: @inputtag , taghistoryid: @taghistoryid%>
</div>
<br>
<% if account_signed_in? %>
  <div id = "button_f">
  <%= render 'mains/button_f', recruitment: @recruitment, view_com_num: @view_com_num %>
  </div>
  <br>
  <div id = "button_f2">
    <% if @view_com_num == '5' %>
      <%= render partial: 'mains/form', locals:{recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num}%>
    <% elsif @view_com_num == '6' %>
      <%= render partial: 'mains/form_r', locals:{recruitment: @recruitment, inputtag: @inputtag, view_com_num: @view_com_num}%>
     <% end %>
  </div>
<% end %>
<div class="button1">
  <div class="on">
<div id="button_v">
  <%= button_to '最新を読み込む', mains_button_view_path(@view_num), method: :get, params:{school:@inputtag.school,faculty:@inputtag.faculty,department:@inputtag.department,tag1:@inputtag.tag1,tag2:@inputtag.tag2,tag3:@inputtag.tag3,tag4:@inputtag.tag4,tag5:@inputtag.tag5,tag6:@inputtag.tag6,tag7:@inputtag.tag7,tag8:@inputtag.tag8,tag9:@inputtag.tag9,tag10:@inputtag.tag10,type:"input"}, remote: true %>
</div>
  </div>
</div>
<br>

<div id="button_v2">
  <%= render 'mains/button_v', view_num: @view_num %>
</div>
<br>
<br>
<div id="button_v3">
  <%= render 'mains/view_t', recruitments: @recruitments %>
</div>

<div class="button1">
  <div class="on">
<div id="button_v4">
  <%= button_to "もっと読み込む", mains_add_path(@recruitments.size.to_s), method: :get, remote: true %>
</div>
  </div>
</div>
</span>