config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks, only: [:create, :destroy]

  devise_for :accounts, :controllers =>{
      :registrations => 'accounts/registrations'
  }

  devise_scope :account do
    post '/accounts/sign_up/confirm', to: 'accounts/registrations#confirm'
    delete '/accounts/:id', to: 'accounts/registrations#destroy', as: :account_destroy, constraints: {id: /[0-9]+/ }
  end

  resources :recruitments, only: [ :edit, :update, :destroy ]
  post '/recruitments/create/:id', to: 'recruitments#create', as: :recruitments_create
  post '/recruitments/:id', to: 'recruitments#update', constraints: {id: /[0-9]+/ }
  # 返信追加読み込み
  post '/recruitments/edit/add/:id/:offset_time', to: 'recruitments#add_result', as: :results_add, constraints: { id:/[0-9]+/ }
  post '/recruitments/select/:id/:comment_id', to: 'recruitments#select', as: :select_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }
  post '/recruitments/selected/:id/:comment_id', to: 'recruitments#selected', as: :selected_result, constraints: { id:/[0-9]+/, comment_id:/[0-9]+/ }

# 返信生成削除
  resources :comments, only: [ :create, :destroy ]
  get '/comments/index/:recruitment_id', to: 'comments#index', as: :comments_index, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/comments/index/add/:recruitment_id/:offset_time', to: 'comments#add_index', as: :comments_add, constraints: { recruitment_id:/[0-9]+/ }
  
  resources :chat_comments, only: [:destroy]
  get '/chat_comments/:recruitment_id', to: 'chat_comments#index', as: :chat_comments_index
  post '/chat_comments/create/:chat_id', to: 'chat_comments#create', as: :chat_comments_create

  resources :entry_chats, only: [:create, :destroy]
  # チャット有り結果選択
  get '/entry_chats/new/:recruitment_id', to: 'entry_chats#new', as: :new_entry_chats, constraints: { recruitment_id: /[0-9]+/ }
  # 返信追加読み込み
  post '/entry_chats/new/add/:recruitment_id/:offset_time', to: 'entry_chats#add_result', as: :results_chat_add, constraints: { recruitment_id:/[0-9]+/ }

  root 'mains#index'

  get 'home/:acc_id', to: 'home#show', as: :account_show
  get '/home/button/:acc_id/:id', to: 'home#button', as: 'home_button'
  get 'home/delete/:acc_id', to: 'home#delete', as: :account_delete
  get '/home/button_view/:acc_id/:id', to: 'home#button_view', as: :home_button_view

  post '/' => 'tags#update'#タグ検索フォーム

  get '/mains/button_view/:id', to: 'mains#button_view', as: :mains_button_view
  get '/mains/button_form/:id', to: 'mains#button_form', as: :mains_button_form
  get '/mains/index/add/:size', to: 'mains#add_index', as: :mains_add, constraints: { size: /[0-9]+/ }

  get '/members/:chat_id', to: 'members#index', as: 'members'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/univtag/list', to: 'univtag#list' #タグ取得用

  get '/verify/recruit', to: 'verify#recruit' #検証用
  get '/verify/recruit2', to: 'verify#recruit2'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
 # has_one :account
 # belongs_to :recruitment

  # photoをattachファイルとする。stylesで画像サイズを定義できる
  has_attached_file :photo,# styles: { medium: "300x300>"},
  :url  => "/assets/arts/:id/:style/:basename.:extension", # 画像保存先のURL先
      :path => "#{Rails.root}/public/assets/arts/:id/:style/:basename.:extension" # サーバ上の画像保存先パス

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif","application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
                       presence: true,  # ファイルの存在チェック
                       less_than: 5.megabytes# ファイルサイズのチェック

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
end
  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save


        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:photo,:name)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_with(model: recruitment, local: true) do |form| %>
  <% if recruitment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruitment.errors.count, "error") %> prohibited this recruitment from being saved:</h2>

      <ul>
      <% recruitment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.file_field :photo %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Recruitment</h1>

<%= render 'form', recruitmente: @recruitment %>

<%= link_to 'ファイルを見る', recruitment %> |
<%= link_to '戻る', recruitments_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ファイル</h1>

<table>
  <thead>
    <tr>
      <th>説明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% recruitments.each do |recruitment| %>
      <tr>
        <td><%= recruitment.name %></td>
        <td><%= link_to '見る', recruitment %></td>
        <td><%= link_to '編集', edit_recruitment_path(recruitment) %></td>
        <td><%= link_to '削除', recruitment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ファイルをアップロードする', new_recruitment_path %>

app/views/pictures/new.html.erb
<h1>アップロードするファイルを選択</h1>

<%= render 'form', recruitment: @picture %>

<%= link_to '戻る',recruitments_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '編集', edit_recruitment_path(@picture) %> |
<%= link_to '戻る', recruitments_path %>
<p>

<!-- 追加箇所 開始-->
<p>
  <strong>File:</strong>
  <!--- Modelのstyleで指定した :midium など渡すことでサイズを指定できる -->
  <%= link_to 'ファイルを表示する', @recruitment.photo.url%>
</p>
<!-- 追加箇所 終了-->